import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1787556591758 implements MigrationInterface {
    name = 'InitialSchema1787556591758'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS "uuid-ossp"`);
        await queryRunner.query(`CREATE TYPE "public"."verifications_status_enum" AS ENUM('pending', 'approved', 'rejected', 'expired')`);
        await queryRunner.query(`CREATE TABLE "verifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "identityId" character varying NOT NULL, "walletAddress" character varying NOT NULL, "proofHash" character varying NOT NULL, "verificationCommitment" character varying NOT NULL, "status" "public"."verifications_status_enum" NOT NULL DEFAULT 'pending', "reason" character varying, "expiresAt" TIMESTAMP WITH TIME ZONE, "metadata" json, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2127ad1b143cf012280390b01d1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2e31645aac05e5b108d321042d" ON "verifications" ("identityId") `);
        await queryRunner.query(`CREATE INDEX "IDX_64099fd2aafd220c32a480a439" ON "verifications" ("walletAddress") `);
        await queryRunner.query(`CREATE TYPE "public"."role_assignments_role_enum" AS ENUM('viewer', 'verifier', 'issuer', 'admin')`);
        await queryRunner.query(`CREATE TABLE "role_assignments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "granteeAddress" character varying NOT NULL, "role" "public"."role_assignments_role_enum" NOT NULL, "resourceId" character varying NOT NULL DEFAULT '*', "grantedByAddress" character varying NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "expiresAt" TIMESTAMP WITH TIME ZONE, "grantedAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_fc2df9835ac1d2a34839f113783" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c9d9f1f1983bde0720a6047d18" ON "role_assignments" ("granteeAddress") `);
        await queryRunner.query(`CREATE INDEX "IDX_0fe58a810ad39c1f2eb41ac5e4" ON "role_assignments" ("resourceId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_7af9f9b4f800572efdc68dd6a6" ON "role_assignments" ("granteeAddress", "resourceId", "role") `);
        await queryRunner.query(`CREATE TABLE "identities" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "walletAddress" character varying NOT NULL, "documentHash" character varying NOT NULL, "ipfsCid" character varying NOT NULL, "verificationStatus" boolean NOT NULL DEFAULT false, "revoked" boolean NOT NULL DEFAULT false, "revocationReason" character varying, "metadata" json, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7b2f8cccf4ac6a2d7e6e9e8b1f6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."health_authorities_authtype_enum" AS ENUM('api_key', 'oauth2', 'mutual_tls', 'jwt_bearer')`);
        await queryRunner.query(`CREATE TYPE "public"."health_authorities_status_enum" AS ENUM('active', 'inactive', 'suspended', 'pending_verification')`);
        await queryRunner.query(`CREATE TABLE "health_authorities" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "apiUrl" character varying NOT NULL, "authType" "public"."health_authorities_authtype_enum" NOT NULL, "status" "public"."health_authorities_status_enum" NOT NULL DEFAULT 'pending_verification', "apiKey" character varying, "clientId" character varying, "clientSecret" character varying, "tokenUrl" character varying, "certificatePath" character varying, "jurisdiction" character varying, "accessToken" character varying, "tokenExpiresAt" TIMESTAMP WITH TIME ZONE, "metadata" json, "credentialsIssued" integer NOT NULL DEFAULT '0', "lastConnectedAt" TIMESTAMP WITH TIME ZONE, "lastError" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_091c95d7437b6fa771e71c9d4f9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a12fc85b426c020664339756b8" ON "health_authorities" ("name") `);
        await queryRunner.query(`CREATE TYPE "public"."issuance_records_format_enum" AS ENUM('w3c_vc', 'fhir', 'hl7', 'custom_json', 'smart_health_card')`);
        await queryRunner.query(`CREATE TYPE "public"."issuance_records_status_enum" AS ENUM('pending', 'processing', 'issued', 'failed', 'revoked')`);
        await queryRunner.query(`CREATE TABLE "issuance_records" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "authorityId" uuid NOT NULL, "patientWalletAddress" character varying NOT NULL, "credentialType" character varying NOT NULL, "format" "public"."issuance_records_format_enum" NOT NULL DEFAULT 'custom_json', "status" "public"."issuance_records_status_enum" NOT NULL DEFAULT 'pending', "healthData" json NOT NULL, "issuedCredential" json, "credentialHash" character varying, "externalRequestId" character varying, "expirationDate" TIMESTAMP WITH TIME ZONE, "failureReason" character varying, "retryCount" integer NOT NULL DEFAULT '0', "issuerNotes" character varying, "metadata" json, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_39147b30d97d0f56755a0582e87" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8440c70760bbd133bc7284806e" ON "issuance_records" ("authorityId") `);
        await queryRunner.query(`CREATE INDEX "IDX_706ccfe85d207fabd3b966c5ba" ON "issuance_records" ("patientWalletAddress") `);
        await queryRunner.query(`CREATE TABLE "shared_data" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "ownerAddress" character varying NOT NULL, "recipientAddress" character varying NOT NULL, "documentHash" character varying NOT NULL, "encryptedKey" text NOT NULL, "accessExpiry" integer NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "metadata" json, "sharedAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_accd282bee89d94697d4c5d7a18" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "credentials" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" character varying NOT NULL, "issuer" character varying NOT NULL, "holder" character varying, "data" json NOT NULL, "status" character varying NOT NULL DEFAULT 'active', "systemSource" character varying, "contentHash" character varying, "duplicateOfId" character varying, "isDuplicate" boolean NOT NULL DEFAULT false, "duplicateMetadata" json, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1e38bc43be6697cdda548ad27a6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9c5dd783b8d84dfbda8fd7b98b" ON "credentials" ("contentHash") `);
        await queryRunner.query(`CREATE TABLE "credential_versions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "credentialId" character varying NOT NULL, "versionNumber" integer NOT NULL, "schemaVersion" character varying NOT NULL DEFAULT '1.0.0', "documentHash" character varying NOT NULL, "ipfsCid" character varying NOT NULL, "verificationStatus" boolean NOT NULL DEFAULT false, "revoked" boolean NOT NULL DEFAULT false, "metadata" json, "changeReason" character varying, "changedBy" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_2d3ddc62358cf21e617ce02a2f1" UNIQUE ("credentialId", "versionNumber"), CONSTRAINT "PK_043316e51edc6dbb84234b3ca53" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8e4ee079a148d3e7fa5ff54b81" ON "credential_versions" ("credentialId") `);
        await queryRunner.query(`CREATE INDEX "IDX_5fa4d1928dc2f0627286589b34" ON "credential_versions" ("versionNumber") `);
        await queryRunner.query(`CREATE INDEX "IDX_ad6b1c640fb1846122557fb962" ON "credential_versions" ("changedBy") `);
        await queryRunner.query(`CREATE TYPE "public"."credential_migrations_status_enum" AS ENUM('pending', 'success', 'failed', 'conflict', 'resolved')`);
        await queryRunner.query(`CREATE TABLE "credential_migrations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "credentialId" character varying NOT NULL, "fromVersion" integer NOT NULL, "toVersion" integer, "fromSchemaVersion" character varying NOT NULL, "toSchemaVersion" character varying NOT NULL, "status" "public"."credential_migrations_status_enum" NOT NULL DEFAULT 'pending', "conflictReason" character varying, "resolutionNotes" json, "migratedBy" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e7353148b7b7117d980495905a6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8080932dda76eda6b6b6f5c3d9" ON "credential_migrations" ("credentialId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f07b0520b34fb6b2a02b092c87" ON "credential_migrations" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_77f05bf0e293a614e9f50699e2" ON "credential_migrations" ("migratedBy") `);
        await queryRunner.query(`CREATE TYPE "public"."sharing_history_events_action_enum" AS ENUM('SHARED', 'EXTENDED', 'REVOKED', 'RESTORED')`);
        await queryRunner.query(`CREATE TABLE "sharing_history_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sharedDataId" character varying NOT NULL, "ownerAddress" character varying NOT NULL, "recipientAddress" character varying NOT NULL, "documentHash" character varying NOT NULL, "action" "public"."sharing_history_events_action_enum" NOT NULL, "metadata" json, "timestamp" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_03946915ba39ca6e78a993fffeb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."credential_exports_format_enum" AS ENUM('json', 'csv', 'pdf', 'vc')`);
        await queryRunner.query(`CREATE TYPE "public"."credential_exports_status_enum" AS ENUM('pending', 'processing', 'completed', 'failed')`);
        await queryRunner.query(`CREATE TABLE "credential_exports" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "requestedBy" character varying NOT NULL, "format" "public"."credential_exports_format_enum" NOT NULL, "status" "public"."credential_exports_status_enum" NOT NULL DEFAULT 'pending', "credentialIds" json, "includeMetadata" boolean NOT NULL DEFAULT false, "includeVersionHistory" boolean NOT NULL DEFAULT false, "encryptSensitiveData" boolean NOT NULL DEFAULT true, "encryptionKeyId" character varying, "fileHash" text, "storagePath" text, "credentialCount" integer NOT NULL DEFAULT '0', "fileSizeBytes" bigint NOT NULL DEFAULT '0', "errorMessage" text, "validationResults" json, "completedAt" TIMESTAMP, "expiresAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3644c4337dde931ac4b1650647a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_97e2b96eee5be7d900f71e51cc" ON "credential_exports" ("requestedBy") `);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_operationtype_enum" AS ENUM('issued', 'revoked', 'verified', 'updated', 'deleted', 'shared', 'accessed', 'role_assigned', 'role_revoked')`);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_status_enum" AS ENUM('success', 'failure')`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sequence" BIGSERIAL NOT NULL, "actorId" character varying NOT NULL, "operationType" "public"."audit_logs_operationtype_enum" NOT NULL, "targetCredentialId" character varying, "clientIp" character varying, "status" "public"."audit_logs_status_enum" NOT NULL DEFAULT 'success', "metadata" json, "previousHash" character varying(64), "hash" character varying(64) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_a1a8da97e76ef043712fdeb694" ON "audit_logs" ("sequence") `);
        await queryRunner.query(`CREATE INDEX "IDX_2dc33f7f3c22e2e7badafca1d1" ON "audit_logs" ("actorId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3f521f4fa46f1e21f3becf021b" ON "audit_logs" ("operationType") `);
        await queryRunner.query(`CREATE INDEX "IDX_acdc6af76706ad7d8aa4029e28" ON "audit_logs" ("targetCredentialId") `);
        await queryRunner.query(`CREATE INDEX "IDX_2961862b2704794af56359ff0a" ON "audit_logs" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_c69efb19bf127c97e6740ad530" ON "audit_logs" ("createdAt") `);
        await queryRunner.query(`CREATE TABLE "access_permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "grantorAddress" character varying NOT NULL, "granteeAddress" character varying NOT NULL, "resourceId" character varying NOT NULL, "accessExpiry" integer NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "metadata" json, "grantedAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_82523ed02665644d1f7c79a64fe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "indexed_verifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "verification_id" bigint NOT NULL, "identity_id" bigint NOT NULL, "verifier" character varying(255) NOT NULL, "subject" character varying(255) NOT NULL, "verified" boolean NOT NULL, "proofHash" text, "zkProof" text, "verified_at" bigint NOT NULL, "ledger_timestamp" bigint NOT NULL, "ledger_sequence" bigint NOT NULL, "transaction_hash" character varying(255) NOT NULL, "contract_id" character varying(255) NOT NULL, "indexed_at" TIMESTAMP NOT NULL DEFAULT now(), "metadata" json, CONSTRAINT "PK_2697c5dab48bb1bf74e586e7aac" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8a2cc7affaf3bc4a1144944da9" ON "indexed_verifications" ("verification_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_20133f03833a769b4277650b16" ON "indexed_verifications" ("identity_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_4e0b540710dbc25b421058d4a3" ON "indexed_verifications" ("verifier") `);
        await queryRunner.query(`CREATE INDEX "IDX_0dccc53b17457a35d45e4a9ce7" ON "indexed_verifications" ("subject") `);
        await queryRunner.query(`CREATE INDEX "IDX_3e6ec076a04ea8f3e2f34ba4c3" ON "indexed_verifications" ("ledger_sequence") `);
        await queryRunner.query(`CREATE INDEX "IDX_0e0a146c0c15e8399a7b57d027" ON "indexed_verifications" ("transaction_hash") `);
        await queryRunner.query(`CREATE TABLE "indexed_identities" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "identity_id" bigint NOT NULL, "owner" character varying(255) NOT NULL, "documentHash" character varying(255) NOT NULL, "ipfsCid" text NOT NULL, "verificationStatus" boolean NOT NULL DEFAULT false, "revoked" boolean NOT NULL DEFAULT false, "created_at" bigint NOT NULL, "ledger_timestamp" bigint NOT NULL, "ledger_sequence" bigint NOT NULL, "transaction_hash" character varying(255) NOT NULL, "contract_id" character varying(255) NOT NULL, "indexed_at" TIMESTAMP NOT NULL DEFAULT now(), "metadata" json, CONSTRAINT "PK_ce2e6e3ef7d8090c8fa2ea71756" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d41457404b5f0a360f25385801" ON "indexed_identities" ("identity_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7e467b972045b3faf5bd748cae" ON "indexed_identities" ("owner") `);
        await queryRunner.query(`CREATE INDEX "IDX_fe3a18528380f95d4a8d74bda4" ON "indexed_identities" ("documentHash") `);
        await queryRunner.query(`CREATE INDEX "IDX_e0c9fc81dff0a1cc64c25e2973" ON "indexed_identities" ("ledger_sequence") `);
        await queryRunner.query(`CREATE INDEX "IDX_7fd6ac7d9f7d086f7aedaee886" ON "indexed_identities" ("transaction_hash") `);
        await queryRunner.query(`CREATE TABLE "indexed_data_sharing" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sharing_id" bigint NOT NULL, "identity_id" bigint NOT NULL, "owner" character varying(255) NOT NULL, "recipient" character varying(255) NOT NULL, "encrypted_data" text NOT NULL, "encryption_key_hash" text NOT NULL, "access_revoked" boolean NOT NULL DEFAULT false, "shared_at" bigint NOT NULL, "ledger_timestamp" bigint NOT NULL, "ledger_sequence" bigint NOT NULL, "transaction_hash" character varying(255) NOT NULL, "contract_id" character varying(255) NOT NULL, "indexed_at" TIMESTAMP NOT NULL DEFAULT now(), "metadata" json, CONSTRAINT "PK_6582f2ef54b2498f414fec88ffc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f5401af24836b589ac9640b4bc" ON "indexed_data_sharing" ("sharing_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a4ffe5a7b6c474d9336f42cd1a" ON "indexed_data_sharing" ("identity_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_21dbbd85da6bf2d09b01960933" ON "indexed_data_sharing" ("owner") `);
        await queryRunner.query(`CREATE INDEX "IDX_42c146a31098d47ee019d07691" ON "indexed_data_sharing" ("recipient") `);
        await queryRunner.query(`CREATE INDEX "IDX_d3aae4fd70e25ac21d491c74cd" ON "indexed_data_sharing" ("ledger_sequence") `);
        await queryRunner.query(`CREATE INDEX "IDX_b2dc8aea87149ab251162c77dd" ON "indexed_data_sharing" ("transaction_hash") `);
        await queryRunner.query(`CREATE TABLE "indexed_access_controls" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "access_id" bigint NOT NULL, "identity_id" bigint NOT NULL, "grantor" character varying(255) NOT NULL, "grantee" character varying(255) NOT NULL, "access_granted" boolean NOT NULL, "expires_at" bigint, "granted_at" bigint NOT NULL, "ledger_timestamp" bigint NOT NULL, "ledger_sequence" bigint NOT NULL, "transaction_hash" character varying(255) NOT NULL, "contract_id" character varying(255) NOT NULL, "indexed_at" TIMESTAMP NOT NULL DEFAULT now(), "metadata" json, CONSTRAINT "PK_5d1d5f6a9d44cb909389f303b2a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0422607e1bf990304144128063" ON "indexed_access_controls" ("access_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8b516aad3e21ccfad9d4752797" ON "indexed_access_controls" ("identity_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_99627ee134548e9c4ce2e679c2" ON "indexed_access_controls" ("grantor") `);
        await queryRunner.query(`CREATE INDEX "IDX_44b7ebe0d26d0b73b975facea0" ON "indexed_access_controls" ("grantee") `);
        await queryRunner.query(`CREATE INDEX "IDX_35b780e6d74cb3063054bc807b" ON "indexed_access_controls" ("ledger_sequence") `);
        await queryRunner.query(`CREATE INDEX "IDX_bf109db3e86614b72aa743d441" ON "indexed_access_controls" ("transaction_hash") `);
        await queryRunner.query(`CREATE TYPE "public"."backup_records_backuptype_enum" AS ENUM('full', 'incremental', 'selective')`);
        await queryRunner.query(`CREATE TYPE "public"."backup_records_status_enum" AS ENUM('pending', 'in_progress', 'completed', 'failed', 'restored')`);
        await queryRunner.query(`CREATE TABLE "backup_records" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "walletAddress" character varying NOT NULL, "backupType" "public"."backup_records_backuptype_enum" NOT NULL DEFAULT 'full', "status" "public"."backup_records_status_enum" NOT NULL DEFAULT 'pending', "ipfsCid" character varying NOT NULL, "sizeBytes" bigint NOT NULL, "manifest" json, "checksum" character varying, "errorMessage" character varying, "restoreAttempts" integer NOT NULL DEFAULT '0', "lastRestoreTest" TIMESTAMP WITH TIME ZONE, "isRotatable" boolean NOT NULL DEFAULT true, "retentionDays" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_13c40e36547fe8bc4903891715b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a0d8320885495e194aa13f222b" ON "backup_records" ("walletAddress") `);
        await queryRunner.query(`CREATE TABLE "backup_configs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "walletAddress" character varying NOT NULL, "autoBackupEnabled" boolean NOT NULL DEFAULT true, "backupIntervalHours" integer NOT NULL DEFAULT '24', "retentionDays" integer NOT NULL DEFAULT '30', "maxBackupsToKeep" integer NOT NULL DEFAULT '10', "healthMonitoringEnabled" boolean NOT NULL DEFAULT true, "healthCheckIntervalHours" integer NOT NULL DEFAULT '6', "alertsEnabled" boolean NOT NULL DEFAULT true, "alertWebhookUrl" json, "rotationEnabled" boolean NOT NULL DEFAULT true, "rotationCheckIntervalDays" integer NOT NULL DEFAULT '7', "restorationTestEnabled" boolean NOT NULL DEFAULT true, "restorationTestIntervalDays" integer NOT NULL DEFAULT '30', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_f7ae51b8b3f0328c8a1b7e0289a" UNIQUE ("walletAddress"), CONSTRAINT "PK_25d918dbd367dcb0831412b7b85" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f7ae51b8b3f0328c8a1b7e0289" ON "backup_configs" ("walletAddress") `);
        await queryRunner.query(`CREATE TYPE "public"."backup_alerts_alerttype_enum" AS ENUM('backup_failed', 'backup_health_warning', 'backup_rotation_executed', 'restoration_test_failed', 'storage_quota_warning')`);
        await queryRunner.query(`CREATE TYPE "public"."backup_alerts_severity_enum" AS ENUM('low', 'medium', 'high', 'critical')`);
        await queryRunner.query(`CREATE TABLE "backup_alerts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "walletAddress" character varying NOT NULL, "alertType" "public"."backup_alerts_alerttype_enum" NOT NULL, "severity" "public"."backup_alerts_severity_enum" NOT NULL DEFAULT 'low', "message" text NOT NULL, "metadata" json, "acknowledged" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_922a9e071b34879abfc1934c6a5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_01a416e1df5c81b855c98be1ee" ON "backup_alerts" ("walletAddress") `);
        await queryRunner.query(`ALTER TABLE "issuance_records" ADD CONSTRAINT "FK_8440c70760bbd133bc7284806e2" FOREIGN KEY ("authorityId") REFERENCES "health_authorities"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "issuance_records" DROP CONSTRAINT "FK_8440c70760bbd133bc7284806e2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_01a416e1df5c81b855c98be1ee"`);
        await queryRunner.query(`DROP TABLE "backup_alerts"`);
        await queryRunner.query(`DROP TYPE "public"."backup_alerts_severity_enum"`);
        await queryRunner.query(`DROP TYPE "public"."backup_alerts_alerttype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f7ae51b8b3f0328c8a1b7e0289"`);
        await queryRunner.query(`DROP TABLE "backup_configs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a0d8320885495e194aa13f222b"`);
        await queryRunner.query(`DROP TABLE "backup_records"`);
        await queryRunner.query(`DROP TYPE "public"."backup_records_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."backup_records_backuptype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bf109db3e86614b72aa743d441"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_35b780e6d74cb3063054bc807b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_44b7ebe0d26d0b73b975facea0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_99627ee134548e9c4ce2e679c2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8b516aad3e21ccfad9d4752797"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0422607e1bf990304144128063"`);
        await queryRunner.query(`DROP TABLE "indexed_access_controls"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b2dc8aea87149ab251162c77dd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d3aae4fd70e25ac21d491c74cd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_42c146a31098d47ee019d07691"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_21dbbd85da6bf2d09b01960933"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a4ffe5a7b6c474d9336f42cd1a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f5401af24836b589ac9640b4bc"`);
        await queryRunner.query(`DROP TABLE "indexed_data_sharing"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7fd6ac7d9f7d086f7aedaee886"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e0c9fc81dff0a1cc64c25e2973"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fe3a18528380f95d4a8d74bda4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7e467b972045b3faf5bd748cae"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d41457404b5f0a360f25385801"`);
        await queryRunner.query(`DROP TABLE "indexed_identities"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0e0a146c0c15e8399a7b57d027"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3e6ec076a04ea8f3e2f34ba4c3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0dccc53b17457a35d45e4a9ce7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4e0b540710dbc25b421058d4a3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_20133f03833a769b4277650b16"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8a2cc7affaf3bc4a1144944da9"`);
        await queryRunner.query(`DROP TABLE "indexed_verifications"`);
        await queryRunner.query(`DROP TABLE "access_permissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c69efb19bf127c97e6740ad530"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2961862b2704794af56359ff0a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_acdc6af76706ad7d8aa4029e28"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3f521f4fa46f1e21f3becf021b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2dc33f7f3c22e2e7badafca1d1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a1a8da97e76ef043712fdeb694"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_operationtype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97e2b96eee5be7d900f71e51cc"`);
        await queryRunner.query(`DROP TABLE "credential_exports"`);
        await queryRunner.query(`DROP TYPE "public"."credential_exports_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."credential_exports_format_enum"`);
        await queryRunner.query(`DROP TABLE "sharing_history_events"`);
        await queryRunner.query(`DROP TYPE "public"."sharing_history_events_action_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_77f05bf0e293a614e9f50699e2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f07b0520b34fb6b2a02b092c87"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8080932dda76eda6b6b6f5c3d9"`);
        await queryRunner.query(`DROP TABLE "credential_migrations"`);
        await queryRunner.query(`DROP TYPE "public"."credential_migrations_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ad6b1c640fb1846122557fb962"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5fa4d1928dc2f0627286589b34"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8e4ee079a148d3e7fa5ff54b81"`);
        await queryRunner.query(`DROP TABLE "credential_versions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9c5dd783b8d84dfbda8fd7b98b"`);
        await queryRunner.query(`DROP TABLE "credentials"`);
        await queryRunner.query(`DROP TABLE "shared_data"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_706ccfe85d207fabd3b966c5ba"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8440c70760bbd133bc7284806e"`);
        await queryRunner.query(`DROP TABLE "issuance_records"`);
        await queryRunner.query(`DROP TYPE "public"."issuance_records_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."issuance_records_format_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a12fc85b426c020664339756b8"`);
        await queryRunner.query(`DROP TABLE "health_authorities"`);
        await queryRunner.query(`DROP TYPE "public"."health_authorities_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."health_authorities_authtype_enum"`);
        await queryRunner.query(`DROP TABLE "identities"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7af9f9b4f800572efdc68dd6a6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0fe58a810ad39c1f2eb41ac5e4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c9d9f1f1983bde0720a6047d18"`);
        await queryRunner.query(`DROP TABLE "role_assignments"`);
        await queryRunner.query(`DROP TYPE "public"."role_assignments_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_64099fd2aafd220c32a480a439"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2e31645aac05e5b108d321042d"`);
        await queryRunner.query(`DROP TABLE "verifications"`);
        await queryRunner.query(`DROP TYPE "public"."verifications_status_enum"`);
    }

}
